live_config_reload = true

[color_schemes.OneNord.bright]
black = "#4c566a"
blue = "#81a1c1"
cyan = "#8fbcbb"
green = "#a3be8c"
magenta = "#b48ead"
red = "#bf616a"
white = "#eceff4"
yellow = "#ebcb8b"

[color_schemes.OneNord.cursor]
cursor = "#d8dee9"
text = "#2e3440"

[color_schemes.OneNord.dim]
black = "#373e4d"
blue = "#68809a"
cyan = "#6d96a5"
green = "#809575"
magenta = "#8c738c"
red = "#94545d"
white = "#aeb3bb"
yellow = "#b29e75"

[color_schemes.OneNord.normal]
black = "#3b4252"
blue = "#81a1c1"
cyan = "#88c0d0"
green = "#a3be8c"
magenta = "#b48ead"
red = "#bf616a"
white = "#e5e9f0"
yellow = "#ebcb8b"

[color_schemes.OneNord.primary]
background = "#2e3440"
dim_foreground = "#a5abb6"
foreground = "#d8dee9"

[color_schemes.OneNord.search."colors.footer_bar"]
background = "#434c5e"
foreground = "#d8dee9"

[color_schemes.OneNord.search.matches]
background = "#88c0d0"
foreground = "CellBackground"

[color_schemes.OneNord.selection]
background = "#4c566a"
text = "CellForeground"

[color_schemes.OneNord.vi_mode_cursor]
cursor = "#d8dee9"
text = "#2e3440"

[color_schemes.frappe.bright]
black = "#51576D"
blue = "#8CAAEE"
cyan = "#81C8BE"
green = "#A6D189"
magenta = "#F4B8E4"
red = "#E78284"
white = "#B5BFE2"
yellow = "#E5C890"

[color_schemes.frappe.cursor]
cursor = "#F2D5CF"
text = "#303446"

[color_schemes.frappe.dim]
black = "#51576D"
blue = "#8CAAEE"
cyan = "#81C8BE"
green = "#A6D189"
magenta = "#F4B8E4"
red = "#E78284"
white = "#B5BFE2"
yellow = "#E5C890"

[color_schemes.frappe.hints.end]
background = "#A5ADCE"
foreground = "#303446"

[color_schemes.frappe.hints.start]
background = "#E5C890"
foreground = "#303446"

[color_schemes.frappe.normal]
black = "#51576D"
blue = "#8CAAEE"
cyan = "#81C8BE"
green = "#A6D189"
magenta = "#F4B8E4"
red = "#E78284"
white = "#B5BFE2"
yellow = "#E5C890"

[color_schemes.frappe.primary]
background = "#303446"
bright_foreground = "#C6D0F5"
dim_foreground = "#C6D0F5"
foreground = "#C6D0F5"

[color_schemes.frappe.search."colors.footer_bar"]
background = "#A5ADCE"
foreground = "#303446"

[color_schemes.frappe.search.focused_match]
background = "#A6D189"
foreground = "#303446"

[color_schemes.frappe.search.matches]
background = "#A5ADCE"
foreground = "#303446"

[color_schemes.frappe.selection]
background = "#F2D5CF"
text = "#303446"

[color_schemes.frappe.vi_mode_cursor]
cursor = "#BABBF1"
text = "#303446"

[color_schemes.latte.bright]
black = "#4C4F69"
blue = "#1E66F5"
cyan = "#179299"
green = "#40A02B"
magenta = "#EA76CB"
red = "#D20F39"
white = "#ACB0BE"
yellow = "#DF8E1D"

[color_schemes.latte.cursor]
cursor = "#DC8A78"
text = "#EFF1F5"

[color_schemes.latte.dim]
black = "#4C4F69"
blue = "#1E66F5"
cyan = "#179299"
green = "#40A02B"
magenta = "#EA76CB"
red = "#D20F39"
white = "#ACB0BE"
yellow = "#DF8E1D"

[color_schemes.latte.hints.end]
background = "#6C6F85"
foreground = "#EFF1F5"

[color_schemes.latte.hints.start]
background = "#DF8E1D"
foreground = "#EFF1F5"

[color_schemes.latte.normal]
black = "#4C4F69"
blue = "#1E66F5"
cyan = "#179299"
green = "#40A02B"
magenta = "#EA76CB"
red = "#D20F39"
white = "#ACB0BE"
yellow = "#DF8E1D"

[color_schemes.latte.primary]
background = "#EFF1F5"
bright_foreground = "#4C4F69"
dim_foreground = "#4C4F69"
foreground = "#4C4F69"

[color_schemes.latte.search."colors.footer_bar"]
background = "#6C6F85"
foreground = "#EFF1F5"

[color_schemes.latte.search.focused_match]
background = "#40A02B"
foreground = "#EFF1F5"

[color_schemes.latte.search.matches]
background = "#6C6F85"
foreground = "#EFF1F5"

[color_schemes.latte.selection]
background = "#DC8A78"
text = "#EFF1F5"

[color_schemes.latte.vi_mode_cursor]
cursor = "#7287FD"
text = "#EFF1F5"

[color_schemes.macchiato.bright]
black = "#494D64"
blue = "#8AADF4"
cyan = "#8BD5CA"
green = "#A6DA95"
magenta = "#F5BDE6"
red = "#ED8796"
white = "#B8C0E0"
yellow = "#EED49F"

[color_schemes.macchiato.cursor]
cursor = "#F4DBD6"
text = "#24273A"

[color_schemes.macchiato.dim]
black = "#494D64"
blue = "#8AADF4"
cyan = "#8BD5CA"
green = "#A6DA95"
magenta = "#F5BDE6"
red = "#ED8796"
white = "#B8C0E0"
yellow = "#EED49F"

[color_schemes.macchiato.hints.end]
background = "#A5ADCB"
foreground = "#24273A"

[color_schemes.macchiato.hints.start]
background = "#EED49F"
foreground = "#24273A"

[color_schemes.macchiato.normal]
black = "#494D64"
blue = "#8AADF4"
cyan = "#8BD5CA"
green = "#A6DA95"
magenta = "#F5BDE6"
red = "#ED8796"
white = "#B8C0E0"
yellow = "#EED49F"

[color_schemes.macchiato.primary]
background = "#24273A"
bright_foreground = "#CAD3F5"
dim_foreground = "#CAD3F5"
foreground = "#CAD3F5"

[color_schemes.macchiato.search."colors.footer_bar"]
background = "#A5ADCB"
foreground = "#24273A"

[color_schemes.macchiato.search.focused_match]
background = "#A6DA95"
foreground = "#24273A"

[color_schemes.macchiato.search.matches]
background = "#A5ADCB"
foreground = "#24273A"

[color_schemes.macchiato.selection]
background = "#F4DBD6"
text = "#24273A"

[color_schemes.macchiato.vi_mode_cursor]
cursor = "#B7BDF8"
text = "#24273A"

[color_schemes.mocha.bright]
black = "#45475A"
blue = "#89B4FA"
cyan = "#94E2D5"
green = "#A6E3A1"
magenta = "#F5C2E7"
red = "#F38BA8"
white = "#BAC2DE"
yellow = "#F9E2AF"

[color_schemes.mocha.cursor]
cursor = "#F5E0DC"
text = "#1E1E2E"

[color_schemes.mocha.dim]
black = "#45475A"
blue = "#89B4FA"
cyan = "#94E2D5"
green = "#A6E3A1"
magenta = "#F5C2E7"
red = "#F38BA8"
white = "#BAC2DE"
yellow = "#F9E2AF"

[color_schemes.mocha.hints.end]
background = "#A6ADC8"
foreground = "#1E1E2E"

[color_schemes.mocha.hints.start]
background = "#F9E2AF"
foreground = "#1E1E2E"

[color_schemes.mocha.normal]
black = "#45475A"
blue = "#89B4FA"
cyan = "#94E2D5"
green = "#A6E3A1"
magenta = "#F5C2E7"
red = "#F38BA8"
white = "#BAC2DE"
yellow = "#F9E2AF"

[color_schemes.mocha.primary]
background = "#1E1E2E"
bright_foreground = "#CDD6F4"
dim_foreground = "#CDD6F4"
foreground = "#CDD6F4"

[color_schemes.mocha.search."colors.footer_bar"]
background = "#A6ADC8"
foreground = "#1E1E2E"

[color_schemes.mocha.search.focused_match]
background = "#A6E3A1"
foreground = "#1E1E2E"

[color_schemes.mocha.search.matches]
background = "#A6ADC8"
foreground = "#1E1E2E"

[color_schemes.mocha.selection]
background = "#F5E0DC"
text = "#1E1E2E"

[color_schemes.mocha.vi_mode_cursor]
cursor = "#B4BEFE"
text = "#1E1E2E"

[colors.bright]
black = "#45475A"
blue = "#89B4FA"
cyan = "#94E2D5"
green = "#A6E3A1"
magenta = "#F5C2E7"
red = "#F38BA8"
white = "#BAC2DE"
yellow = "#F9E2AF"

[colors.cursor]
cursor = "#F5E0DC"
text = "#1E1E2E"

[colors.dim]
black = "#45475A"
blue = "#89B4FA"
cyan = "#94E2D5"
green = "#A6E3A1"
magenta = "#F5C2E7"
red = "#F38BA8"
white = "#BAC2DE"
yellow = "#F9E2AF"

[colors.hints.end]
background = "#A6ADC8"
foreground = "#1E1E2E"

[colors.hints.start]
background = "#F9E2AF"
foreground = "#1E1E2E"

[colors.normal]
black = "#45475A"
blue = "#89B4FA"
cyan = "#94E2D5"
green = "#A6E3A1"
magenta = "#F5C2E7"
red = "#F38BA8"
white = "#BAC2DE"
yellow = "#F9E2AF"

[colors.primary]
background = "#1E1E2E"
bright_foreground = "#CDD6F4"
dim_foreground = "#CDD6F4"
foreground = "#CDD6F4"

[colors.search."colors.footer_bar"]
background = "#A6ADC8"
foreground = "#1E1E2E"

[colors.search.focused_match]
background = "#A6E3A1"
foreground = "#1E1E2E"

[colors.search.matches]
background = "#A6ADC8"
foreground = "#1E1E2E"

[colors.selection]
background = "#F5E0DC"
text = "#1E1E2E"

[colors.vi_mode_cursor]
cursor = "#B4BEFE"
text = "#1E1E2E"

[env]
TERM = "xterm-256color"

[font]
size = 14.0

[font.bold]
family = "SauceCodePro Nerd Font"

[font.bold_italic]
family = "SauceCodePro Nerd Font"

[font.italic]
family = "SauceCodePro Nerd Font"

[font.normal]
family = "SauceCodePro Nerd Font"

[[keyboard.bindings]]
action = "CreateNewWindow"
key = "N"
mods = "Command"

[[keyboard.bindings]]
action = "IncreaseFontSize"
key = "Up"
mods = "Command|Shift"

[[keyboard.bindings]]
action = "DecreaseFontSize"
key = "Down"
mods = "Command|Shift"

[[keyboard.bindings]]
action = "ClearHistory"
key = "L"
mods = "Control"

[scrolling]
history = 100000

[shell]
program = "/bin/zsh"

[window]
decorations = "Transparent"

[window.padding]
x = 5
y = 30
