#!/bin/bash
# current user
CURRENT_USER="$(scutil <<< "show State:/Users/ConsoleUser" | awk '/Name :/ && ! /loginwindow/ {print $3}')"

if [[ "$(uname -m)" == 'arm64' ]]; then
    HOMEBREW_PATH=/opt/homebrew/bin/brew
    echo 'eval "$(/opt/homebrew/bin/brew shellenv)"' >> ~/.zprofile
    eval "$(/opt/homebrew/bin/brew shellenv)"
else
    HOMEBREW_PATH=/usr/local/bin/brew
fi

# create directories
mkdir ~/.config
mkdir -p ~/.config/nvim
mkdir ~/.config/alacritty

# create links
# link zshrc and p10k.zsh
ln -nfs ~/git/dotfiles/.zshrc ~/.zshrc
ln -nfs ~/git/dotfiles/.p10k.zsh ~/.p10k.zsh
ln -nfs ~/git/dotfiles/alacritty/alacritty.yml ~/.config/alacritty/alacritty.yml
ln -nfs ~/git/dotfiles/nvim/appearance.vim ~/.config/nvim/appearance.vim
ln -nfs ~/git/dotfiles/nvim/coc.vim ~/.config/nvim/coc.vim
ln -nfs ~/git/dotfiles/nvim/coc-settings.json ~/.config/nvim/coc-settings.json
ln -nfs ~/git/dotfiles/nvim/general.vim ~/.config/nvim/general.vim
ln -nfs ~/git/dotfiles/nvim/init.vim ~/.config/nvim/init.vim
ln -nfs ~/git/dotfiles/nvim/keymaps.vim ~/.config/nvim/keymaps.vim
ln -nfs ~/git/dotfiles/nvim/lualine.vim ~/.config/nvim/lualine.vim
ln -nfs ~/git/dotfiles/nvim/treesitter.vim ~/.config/nvim/treesitter.vim
ln -nfs ~/git/dotfiles/nvim/vimplug.vim ~/.config/nvim/vimplug.vim
ln -nfs ~/git/dotfiles/nvim/comments.vim ~/.config/nvim/comments.vim
ln -nfs ~/git/dotfiles/nvim/snips ~/.config/nvim/

CASKS=(
    "alacritty"
    "amethyst"
    "google-chrome"
    "firefox"
    "suspicious-package"
    "packages"
    "notion"
    "autodesk-fusion360"
    "prusaslicer"
    "1password"
    "monitorcontrol"
)

FORMULAE=(
    "nvim"
    "bat"
    "ncdu"
    "ffmpeg"
    "git"
    "nmap"
    "shellcheck"
    "ruby"
    "node"
    "yarn"
    "tldr"
    "python3"
    "lazygit"
)


# install brew
/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"

# install casks and formulae
"$HOMEBREW_PATH" install ${FORMULAE[*]}
"$HOMEBREW_PATH" install --cask ${CASKS[*]}

# download dotfiles
git clone https://github.com/tulgeywood/dotfiles.git ~/.config


# install bash language server
npm i -g bash-language-server

# install fonts
"$HOMEBREW_PATH" tap homebrew/cask-fonts
"$HOMEBREW_PATH" install --cask font-sauce-code-pro-nerd-font

# remove alacritty quarantine
sudo xattr -r -d com.apple.quarantine /Applications/Alacritty.app

# install oh-my-zsh
export ZSH=~/.config/.oh-my-zsh

sh -c "$(curl -fsSL https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh)" "" --keep-zshrc --unattended

# oh-my-zsh plugins
git clone https://github.com/zsh-users/zsh-syntax-highlighting.git "$ZSH"/plugins/zsh-syntax-highlighting
git clone https://github.com/zsh-users/zsh-autosuggestions "$ZSH"/plugins/zsh-autosuggestions
git clone --depth=1 https://github.com/romkatv/powerlevel10k.git "$ZSH"/themes/powerlevel10k

# pip installs
python3 -m pip install --user --upgrade pynvim

# install nvim plugins
nvim --headless +PlugInstall +qall
nvim --headless +PlugInstall +qall
nvim --headless +"CocInstall -sync coc-diagnostic coc-json coc-python coc-snippets|qa"

# source zshrc
source .zshrc
